-- Baseline PostgreSQL schema mirroring the Build C SQLite data model.
-- Application timestamps stay ISO-8601 TEXT so values import byte-for-byte.

CREATE TABLE users (
    name         TEXT PRIMARY KEY,
    salt         TEXT NOT NULL,
    hash         TEXT NOT NULL,
    display_name TEXT NOT NULL DEFAULT ''
);

CREATE TABLE sessions (
    token   TEXT PRIMARY KEY,
    name    TEXT REFERENCES users(name),
    expires BIGINT NOT NULL
);

CREATE TABLE records (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind    TEXT NOT NULL CHECK (kind IN ('tasks','posts','requests','events','lists','dance','notes','recognitions','activities')),
    body    JSONB NOT NULL CHECK (jsonb_typeof(body) = 'object'),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE audit (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor     TEXT,
    record_id BIGINT REFERENCES records(id),
    action    TEXT,
    created   TEXT,
    snapshot  JSONB NOT NULL DEFAULT '{}'::jsonb,
    details   JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE attempts (
    address TEXT PRIMARY KEY,
    count   INTEGER,
    reset   BIGINT
);

CREATE TABLE recurrence_series (
    series_id       BIGINT PRIMARY KEY REFERENCES records(id),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    rule            JSONB NOT NULL,
    start_date      TEXT NOT NULL,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    created_by      TEXT NOT NULL DEFAULT '',
    anchor_sequence INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE recurrence_occurrences (
    series_id       BIGINT NOT NULL REFERENCES recurrence_series(series_id),
    occurrence_date TEXT NOT NULL,
    task_id         BIGINT NOT NULL UNIQUE REFERENCES records(id),
    sequence        INTEGER NOT NULL,
    PRIMARY KEY (series_id, occurrence_date)
);

-- source_id is deliberately not a foreign key: some reminder sources (e.g. weekly recap) are not records.
CREATE TABLE reminders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account        TEXT NOT NULL REFERENCES users(name),
    source_kind    TEXT NOT NULL,
    source_id      BIGINT NOT NULL,
    reminder_key   TEXT NOT NULL,
    reminder_type  TEXT NOT NULL,
    due_at         TEXT NOT NULL,
    created_at     TEXT NOT NULL,
    read_at        TEXT,
    dismissed_at   TEXT,
    snoozed_until  TEXT,
    UNIQUE (account, source_kind, source_id, reminder_key)
);

CREATE TABLE recognition_receipts (
    recognition_id BIGINT NOT NULL REFERENCES records(id),
    recipient      TEXT NOT NULL REFERENCES users(name),
    seen_at        TEXT NOT NULL,
    PRIMARY KEY (recognition_id, recipient)
);

CREATE TABLE notification_settings (
    name  TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Profiles are distinct from authenticated users: managed children (e.g. Maddox) never have a users row.
CREATE TABLE family_members (
    member_id    TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    member_type  TEXT NOT NULL CHECK (member_type IN ('account','managed_child')),
    account_name TEXT UNIQUE REFERENCES users(name),
    managed_by   JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(managed_by) = 'array'),
    avatar       TEXT NOT NULL DEFAULT '',
    CHECK ((member_type = 'account') = (account_name IS NOT NULL))
);
