// Remove V1 browser-only data; authenticated data is never persisted here.
try{localStorage.removeItem('mrhub')}catch{}
let S={viewer:'',profiles:{},tasks:[],posts:[],requests:[],events:[],lists:[],dance:[],notes:[],activity:[],streak:0,points:0};const save=()=>{};const adult=v=>v==='Dad'||v==='Mom';const visible=t=>t.visibility==='Family'||(t.visibility==='Adults'&&adult(S.viewer))||(t.visibility==='Assigned'&&(t.who===S.viewer||t.who==='Everyone'))||(t.visibility==='Me'&&t.creator===S.viewer);const displayName=id=>S.profiles?.[id]?.displayName||id;const displayAssignee=id=>id? id==='Everyone'?'Everyone':displayName(id):'Unassigned';const visibilityName=id=>({Family:'Family / Everyone',Adults:'Adults Only',Assigned:'Assigned Person',Me:'Me Only'}[id]||id);function displayReply(r){if(!r.reply)return '';const old=r.reply.match(/^(Dad|Mom|Daughter):\s*/);const by=r.replyBy||old?.[1];return by?`${displayName(by)}: ${old?r.reply.slice(old[0].length):r.reply}`:r.reply}function nav(){let daughter=S.viewer==='Daughter';return `<div class=nav><div class=navin>${[['home','🏠','Home'],['tasks','✅',daughter?'My Stuff':'Tasks'],['dance','💃','Dance'],[daughter?'ask':'board',daughter?'🙋':'📣',daughter?'Ask':'Board'],['family','👨‍👩‍👧','Family']].map(x=>`<button onclick="render('${x[0]}')" class="${page===x[0]?'active':''}"><span class=e>${x[1]}</span>${x[2]}</button>`).join('')}</div></div>`}let page='home';function renderTopBar(){return `<div class=top><div><div class=brand>✨ Martin-Riley Family Hub</div><div class=sub>Our little corner of the world · <span id=syncStatus>Connected</span></div></div><button class=btn onclick="logout()">Sign out<br><small>${displayName(S.viewer)}</small></button></div>`}
const taskFilterState={status:'Open',assignee:'All',priority:'All',category:'All'};
let editingTaskId=null;
function openAdd(){editingTaskId=null;openTaskForm()}
const taskById=id=>S.tasks.find(t=>t.id===Number(id));
function taskOverdue(t){if(t.status!=='open'||!t.dueDate)return false;const [year,month,day]=t.dueDate.split('-').map(Number),[hour,minute]=String(t.dueTime||'23:59').split(':').map(Number);const due=new Date(year,month-1,day,hour,minute);return !Number.isNaN(due.valueOf())&&due.valueOf()<Date.now()}
function taskAwaitingAcknowledgement(t){if(!t.ack)return false;const people=t.who==='Everyone'?['Dad','Mom','Daughter']:t.who?[t.who]:[t.creator];return people.some(person=>person&&!(t.acked||[]).includes(person))}
function taskStatus(t){if(t.status==='done')return 'Completed';if(t.status==='missed')return 'Not Completed';const required=t.who&&t.who!=='Everyone'?t.who:S.viewer;if(t.ack&&!(t.acked||[]).includes(required))return 'Needs Acknowledgement';if(taskOverdue(t))return 'Overdue';return 'To Do'}
function timeLabel(value){if(!value)return 'Not recorded';const date=new Date(value);if(Number.isNaN(date.valueOf()))return value;const seconds=Math.floor((Date.now()-date.valueOf())/1000);const relative=seconds<60?'just now':seconds<3600?`${Math.floor(seconds/60)}m ago`:seconds<86400?`${Math.floor(seconds/3600)}h ago`:seconds<604800?`${Math.floor(seconds/86400)}d ago`:'';return relative?`${relative} · ${date.toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}`:date.toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}
function activityList(events){return events.map(e=>`<div class="activity-row"><b>${e.summary||e}</b>${e.createdAt?`<time>${timeLabel(e.createdAt)}</time>`:''}</div>`).join('')||'<div class=card>No recent family activity.</div>'}
function canManageTask(t){return adult(S.viewer)&&(t.creator===S.viewer||t.visibility!=='Me')}
function canCompleteTask(t){if(!t.ack)return true;const required=t.who&&t.who!=='Everyone'?t.who:t.who==='Everyone'?S.viewer:t.creator;return !!required&&(t.acked||[]).includes(required)}
function home(){const daughter=S.viewer==='Daughter',open=S.tasks.filter(t=>t.status==='open'),recent=Date.now()-7*86400000,recentlyCompleted=S.tasks.filter(t=>t.status==='done'&&Date.parse(t.completedAt||'')>=recent).length,awaiting=open.filter(t=>taskAwaitingAcknowledgement(t)).length,overdue=open.filter(taskOverdue).length,attention=open.filter(t=>taskOverdue(t)||taskAwaitingAcknowledgement(t)||['Urgent','High','High Priority'].includes(t.priority)).length;return `${renderTopBar()}<div class=hero><h1>${daughter?'🌈 Hey! Ready for a great day?':'☀️ Welcome back, '+displayName(S.viewer)+'!'}</h1><div>${daughter?`🔥 ${S.streak}-day chore streak • 🏆 ${S.points} completed chores`:`${S.requests.filter(r=>r.status==='Pending').length} request waiting`}</div></div>${daughter?'':`<div class="quick-add"><button class="btn primary" onclick="openAdd()">+ Task</button><button class=btn onclick="openItem('events')">+ Event</button><button class=btn onclick="openItem('lists')">+ List Item</button><button class=btn onclick="openItem('private')">+ Note</button></div><div class="summary-grid"><div class="summary-item"><b>${open.length}</b><span>Open</span></div><div class="summary-item"><b>${attention}</b><span>Needs Attention</span></div><div class="summary-item"><b>${awaiting}</b><span>Awaiting Acknowledgement</span></div><div class="summary-item"><b>${overdue}</b><span>Overdue</span></div><div class="summary-item"><b>${recentlyCompleted}</b><span>Recently Completed</span></div></div>`}<div class=grid>${(daughter?[['✅','My Stuff','tasks'],['💃','Dance','dance'],['🙋',`Ask ${displayName('Dad')} & ${displayName('Mom')}`,'ask'],['📣','Family Board','board'],['📅','My Calendar','calendar'],['🌙','Tomorrow Prep','tomorrow'],['🛒','Shared Lists','lists'],['💌','Me Only','private'],['🔔','Reminders','reminders']]:[['🚨','Needs Attention','tasks'],['🙋','Requests','requests'],['📣','Family Board','board'],['📅','Calendar','calendar'],['💃','Dance Hub','dance'],['🌙','Tomorrow Prep','tomorrow'],['📊','Weekly Recap','recap'],['🔐','Privacy','privacy'],['🛒','Shared Lists','lists'],['🔒','Adult Vault','vault'],['💌','Me Only','private'],['🔔','Reminders','reminders']]).map(x=>`<button class="card tile" onclick="render('${x[2]}')"><span class=emoji>${x[0]}</span><b>${x[1]}</b></button>`).join('')}</div>${daughter?`<div class=card>🏅 ${S.points>=10?'Teamwork superstar':S.points>=1?'First win earned!':'Your first achievement is waiting'} · Complete chores to celebrate!</div><div class=section><h2>🌟 Family Chore Board</h2></div>${choreBoard()}<div class=section><h2>Family Activity</h2></div>${activityList(S.activity.slice(0,8))}`:`<div class=section><h2>Today</h2></div>${taskList(open.filter(t=>visible(t)).slice(0,4))}<div class=section><h2>Recent Activity</h2></div>${activityList(S.activity.slice(0,8))}`}`}
function taskList(arr){return arr.map(t=>{const status=taskStatus(t);return `<div class="card task task-card ${status.toLowerCase().replaceAll(' ','-')}" role=button tabindex=0 onclick="openTaskDetails(${t.id})" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();openTaskDetails(${t.id})}"><div class=status-icon>${status==='Completed'?'✅':status==='Not Completed'?'❌':status==='Needs Acknowledgement'?'👀':status==='Overdue'?'⚠️':'⏳'}</div><div class=grow><span class="pill ${t.priority==='Urgent'?'urgent':t.priority==='High'||t.priority==='High Priority'?'high':t.priority==='Important'?'important':''}">${t.priority==='Urgent'?'🚨':t.priority==='High'||t.priority==='High Priority'?'🔴':t.priority==='Important'?'⭐':'•'} ${t.priority}</span><h3>${t.title}</h3>${t.description?`<p>${t.description}</p>`:''}<div class=meta>${displayAssignee(t.who)} • ${visibilityName(t.visibility)}${t.dueDate?' • Due '+t.dueDate:''}${t.dueTime?' at '+t.dueTime:''}${t.category?' • '+t.category:''}${t.repeat&&t.repeat!=='One Time'?' • '+t.repeat:''}</div>${t.status==='done'?`<div class=meta>Completed by ${displayName(t.completedBy)} · ${timeLabel(t.completedAt)}</div>`:''}${t.status==='missed'?`<div class=meta>${t.reason}</div>`:''}<div class=actions>${t.ack&&t.status==='open'&&!(t.acked||[]).includes(S.viewer)&&(t.who===S.viewer||t.who==='Everyone')?`<button class="btn primary" onclick="event.stopPropagation();ack(${t.id})">Acknowledge</button>`:''}${(t.who===S.viewer||t.who==='Everyone')&&t.status==='open'?`<button class="btn good" ${canCompleteTask(t)?'':'disabled'} onclick="event.stopPropagation();done(${t.id})">Complete</button><button class="btn bad" onclick="event.stopPropagation();openMissReason(${t.id},false)">Not complete</button>`:''}</div></div></div>`}).join('')||'<div class=card>🎉 Nothing here right now.</div>'}
function choreBoard(){return taskList(S.tasks.filter(t=>t.visibility==='Family'&&t.status==='open'))}
function taskFilters(){if(!adult(S.viewer))return '';return `<div class="task-filters"><label>Status<select onchange="setTaskFilter('status',this.value)">${['Open','Completed','Not Completed','All'].map(v=>`<option ${taskFilterState.status===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Assigned<select onchange="setTaskFilter('assignee',this.value)">${[['All','All people'],['Dad',displayName('Dad')],['Mom',displayName('Mom')],['Daughter',displayName('Daughter')],['Everyone','Everyone'],['','Unassigned']].map(([v,l])=>`<option value="${v}" ${taskFilterState.assignee===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Priority<select onchange="setTaskFilter('priority',this.value)">${['All',...['Normal','Important','High Priority','Urgent']].map(v=>`<option ${taskFilterState.priority===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Category<select onchange="setTaskFilter('category',this.value)">${['All',...['Home','Dance','School','Bills','Shopping','Appointments','Work','Other']].map(v=>`<option ${taskFilterState.category===v?'selected':''}>${v}</option>`).join('')}</select></label></div>`}
function setTaskFilter(key,value){taskFilterState[key]=value;render('tasks')}
function tasks(){const filtered=S.tasks.filter(t=>visible(t)&&(adult(S.viewer)?(taskFilterState.status==='All'||taskFilterState.status==='Open'&&t.status==='open'||taskFilterState.status==='Completed'&&t.status==='done'||taskFilterState.status==='Not Completed'&&t.status==='missed')&& (taskFilterState.assignee==='All'||t.who===taskFilterState.assignee)&&(taskFilterState.priority==='All'||t.priority===taskFilterState.priority)&&(taskFilterState.category==='All'||t.category===taskFilterState.category):t.status==='open'));return `${renderTopBar()}<div class=section><h2>${S.viewer==='Daughter'?'✅ My Stuff':'✅ Tasks & Chores'}</h2>${adult(S.viewer)?'<button class="btn primary" onclick="openAdd()">+ Add Task</button>':''}</div>${taskFilters()}${taskList(filtered)}`}
function detailRow(label,value){return `<div class=detail-row><dt>${label}</dt><dd>${value||'Not set'}</dd></div>`}
function openTaskDetails(id){const t=taskById(id);if(!t)return;const acknowledgements=(t.acknowledgements||[]).map(a=>`${displayName(a.person)} · ${timeLabel(a.acknowledgedAt)}`).join('<br>')||((t.acked||[]).map(displayName).join(', ')||'No acknowledgements yet');const completions=(t.completionHistory||[]).map(c=>`${displayName(c.completedBy)} · ${timeLabel(c.completedAt)}`).join('<br>');modal(`<h2>${t.title}</h2><p class="status-label ${taskStatus(t).toLowerCase().replaceAll(' ','-')}">${taskStatus(t)}</p><dl class=task-details data-task-id=${t.id}>${detailRow('Description / notes',t.description)}${detailRow('Assigned person',displayAssignee(t.who))}${detailRow('Created by',displayName(t.creator))}${detailRow('Priority',t.priority)}${detailRow('Visibility',visibilityName(t.visibility))}${detailRow('Category',t.category)}${detailRow('Due date',t.dueDate)}${detailRow('Due time',t.dueTime)}${detailRow('Repeat',t.repeat)}${detailRow('Acknowledgement required',t.ack?'Yes':'No')}${detailRow('Acknowledged by',acknowledgements)}${detailRow('Completion status',taskStatus(t))}${detailRow('Completed by',t.completedBy?displayName(t.completedBy):'')}${detailRow('Completed at',t.completedAt?timeLabel(t.completedAt):'')}${detailRow('Completion history',completions)}${detailRow('Not-completed reason',t.reason)}${detailRow('Reason recorded by',t.reasonBy?displayName(t.reasonBy):'')}${detailRow('Reason timestamp',t.reasonAt?timeLabel(t.reasonAt):'')}${detailRow('Created',timeLabel(t.createdAt))}${detailRow('Last updated',`${t.updatedBy?displayName(t.updatedBy)+' · ':''}${timeLabel(t.updatedAt)}`)}</dl>${canManageTask(t)?`<div class=actions><button class=btn onclick="openEditTask(${t.id})">Edit / Reassign</button>${t.status==='open'?`<button class="btn good" ${canCompleteTask(t)?'':'disabled'} onclick="manageComplete(${t.id})">Mark Complete</button><button class="btn bad" onclick="openMissReason(${t.id},true)">Mark Not Complete</button>`:`<button class=btn onclick="reopenTask(${t.id})">Reopen</button>`}<button class="btn bad" onclick="confirmDeleteTask(${t.id})">Delete</button></div>`:''}${!canManageTask(t)&&t.status==='open'&&(t.who===S.viewer||t.who==='Everyone')?`<div class=actions>${t.ack&&!(t.acked||[]).includes(S.viewer)?`<button class="btn primary" onclick="ack(${t.id})">Acknowledge</button>`:''}<button class="btn good" ${canCompleteTask(t)?'':'disabled'} onclick="done(${t.id})">Complete</button><button class="btn bad" onclick="openMissReason(${t.id},false)">Not Complete</button></div>`:''}`)}
function confirmDeleteTask(id){const t=taskById(id);if(!t||!canManageTask(t))return;document.getElementById('modal')?.remove();modal(`<h2>Delete task?</h2><p>Delete “${t.title}”?</p><div class=actions><button class=btn onclick="openTaskDetails(${id})">Cancel</button><button class="btn bad" onclick="mutate({action:'delete',id:${id}},'tasks')">Delete Task</button></div>`)}
function manageComplete(id){return mutate({action:'done',id,manager:true})}
function reopenTask(id){return mutate({action:'reopen',id},'tasks')}
function openMissReason(id,manager){modal(`<h2>Mark Not Completed</h2><div class=field><label for=missReason>Reason</label><select id=missReason><option>Ran out of time</option><option>Waiting on someone/something</option><option>Rescheduled</option><option>No longer needed</option><option>Other</option></select></div><div class=field><label for=missExplanation>Additional explanation (optional)</label><textarea id=missExplanation rows=3 maxlength=1000></textarea></div><div class=actions><button class=btn onclick="openTaskDetails(${id})">Cancel</button><button class="btn bad" onclick="submitNotComplete(${id},${manager})">Save reason</button></div>`)}
function submitNotComplete(id,manager){const reasonCode=val('missReason'),explanation=val('missExplanation');return mutate({action:'miss',id,reasonCode,explanation,...manager?{manager:true}:{}},'tasks')}
function board(){return `${renderTopBar()}<div class=section><h2>📣 Family Bulletin Board</h2><button class=btn onclick=openPost()>+ Post</button></div>${S.posts.map(p=>`<div class="card boardpost"><b>${p.by==='Dad'?'👨':p.by==='Mom'?'👩':'👧'} ${displayName(p.by)}</b><p>${p.text}</p><div class=reactions>${['❤️','👍','😂','🎉'].map(e=>`<button class=reaction onclick="react(${p.id},'${e}')">${e} ${p.reacts[e]||0}</button>`).join('')}</div></div>`).join('')}`}
function ask(){return `${renderTopBar()}<div class=hero><h1>🙋 Ask ${displayName('Dad')} & ${displayName('Mom')}</h1><div>Need permission, a ride, or have a question? Ask us here! 💬</div></div><button class="btn primary" onclick=openAsk()>+ New Request</button><div class=section><h2>My Requests</h2></div>${S.requests.map(r=>`<div class=card><b>${r.type}</b><p>${r.text}</p><div class="status ${r.status.toLowerCase()}">${r.status==='Pending'?'🟡':r.status==='Approved'?'🟢':'🔴'} ${r.status}</div>${r.reply?`<p class=meta>Parent: ${displayReply(r)}</p>`:''}</div>`).join('')}`}
function requests(){return `${renderTopBar()}<div class=section><h2>🙋 Parent Requests Inbox</h2></div>${S.requests.map(r=>`<div class=card><b>${r.type}</b><p>${r.text}</p><div class="status ${r.status.toLowerCase()}">${r.status}</div>${r.status==='Pending'?`<div class=actions><button class="btn good" onclick="requestAction(${r.id},'Approved')">✅ Approve</button><button class="btn bad" onclick="requestAction(${r.id},'Denied')">❌ Deny</button></div>`:''}${r.reply?`<p class=meta>${displayReply(r)}</p>`:''}</div>`).join('')}`}
function dance(){return `${renderTopBar()}<div class=hero><h1>💃 Dance Hub</h1><div>Everything dance, all in one place ✨</div></div><div class=grid>${[['🏠','Dance Home'],['📅','Schedule'],['🩰','Routines'],['🏆','Competitions'],['👗','Costumes'],['✅','Checklists']].map(x=>`<div class="card tile"><span class=emoji>${x[0]}</span><b>${x[1]}</b>${x[1]==='Competitions'?'<div class=meta>Saturday • Schedule Pending ⏳</div>':''}</div>`).join('')}</div>`}
function calendar(){return `${renderTopBar()}<div class=section><h2>📅 Family Calendar</h2></div>${S.events.map(e=>`<div class=card style="margin-bottom:10px"><b>${e.date}</b><p>${e.text}</p></div>`).join('')}`}
function tomorrow(){return `${renderTopBar()}<div class=hero><h1>🌙 Ready for Tomorrow?</h1><div>Pack it, plan it, then relax ✨</div></div>${taskList(S.tasks.filter(t=>visible(t)&&t.status==='open').slice(0,3))}<div class=card><b>📅 Tomorrow</b><p>💃 Dance practice • 5:30 PM</p><p>🎒 School day</p></div>`}
function recap(){const since=new Date(Date.now()-7*86400000).toISOString();const completed=S.tasks.filter(t=>t.status==='done'&&t.completedAt>=since).length;return `${renderTopBar()}<div class=hero><h1>📊 Our Week 🎉</h1><div>Nice teamwork, Martin-Riley family!</div></div><div class=grid><div class=card><div class=emoji>🔥</div><b>${S.streak} day streak</b></div><div class=card><div class=emoji>✅</div><b>${completed} completed in 7 days</b></div><div class=card><div class=emoji>🙋</div><b>${S.requests.filter(r=>r.status==='Approved').length} approved requests total</b></div><div class=card><div class=emoji>🎉</div><b>${S.posts.filter(p=>p.createdAt>=since).length} posts in 7 days</b></div></div>`}
function family(){return `${renderTopBar()}<div class=section><h2>👨‍👩‍👧 Family</h2></div>${['Dad','Mom','Daughter'].map(n=>`<div class="card task"><div class=avatar>${n==='Dad'?'👨':n==='Mom'?'👩':'👧'}</div><div><b>${displayName(n)}</b><div class=meta>${S.profiles?.[n]?.role||'Family Member'}${n==='Daughter'?' • 🔥 '+S.streak+' day streak':''}</div></div></div>`).join('')}<div class=section><h2>${S.viewer==='Daughter'?'Family Activity':'Recent Activity'}</h2></div>${activityList(S.activity.slice(0,8))}`}
function privacy(){return `${renderTopBar()}<div class=section><h2>🔐 Access & Privacy</h2></div><div class=card><b>🤖 ChatGPT default access</b><p>Tasks: Limited read-only</p><p>Family Calendar: Limited read-only</p><p>🔒 Me Only: Blocked</p><p>🔒 Adult Vault: Blocked</p><p>📍 Location: Blocked</p><p>💵 Financial information: Blocked</p></div><div class=card style="margin-top:12px"><b>Visibility rules</b><p>👨‍👩‍👧 Family • 🔒 Adults Only • 👤 Assigned Person • 🔐 Me Only</p></div>`}
function render(p='home'){if(!S.viewer){loginScreen();return}page=p;let fn={home,tasks,board,ask,requests,dance,calendar,tomorrow,recap,family,privacy,lists:()=>collection('lists'),vault:()=>collection('vault'),private:()=>collection('private'),reminders}[p]||home;document.querySelector('#app').innerHTML=`<main class=shell>${fn()}</main>${nav()}`;window.scrollTo(0,0)}
function modal(html){document.getElementById('modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class=modal id=modal onclick="if(event.target===this)this.remove()"><div class=sheet role=dialog aria-modal=true><button class="btn close-sheet" aria-label="Close" onclick="document.getElementById('modal').remove();render(page)">×</button>${html}</div></div>`)}function openTaskForm(){modal(`<h2>+ Add Task</h2><div class=field><label for=nt>Task or chore name</label><input id=nt maxlength=4000 required></div><div class=field><label for=ndesc>Description / notes (optional)</label><textarea id=ndesc rows=3 maxlength=4000></textarea></div><div class=row><div class=field><label for=nw>Assign to</label><select id=nw><option value="">Unassigned</option><option value="Dad">${displayName('Dad')}</option><option value="Mom">${displayName('Mom')}</option><option value="Daughter">${displayName('Daughter')}</option><option value="Everyone">Everyone</option></select></div><div class=field><label for=np>Priority</label><select id=np onchange="if(this.value==='Urgent')document.querySelector('#na').checked=true"><option>Normal</option><option>Important</option><option>High Priority</option><option>Urgent</option></select></div></div><div class=row><div class=field><label for=nv>Visibility</label><select id=nv><option value="Family">Family / Everyone</option><option value="Adults">Adults Only</option><option value="Assigned">Assigned Person</option><option value="Me">Me Only</option></select></div><div class=field><label for=nc>Category</label><select id=nc><option>Home</option><option>Dance</option><option>School</option><option>Bills</option><option>Shopping</option><option>Appointments</option><option>Work</option><option>Other</option></select></div></div><div class=row><div class=field><label for=nd>Due date</label><input id=nd type=date></div><div class=field><label for=ntime>Due time</label><input id=ntime type=time></div></div><div class=field><label for=nr>Repeat</label><select id=nr><option>One Time</option><option>Daily</option><option>Weekdays</option><option>Weekly</option><option>Monthly</option><option>Custom</option></select></div><label class=toggle><input type=checkbox id=na> Require acknowledgement</label><div class=actions><button class="btn primary" onclick=addTask()>+ Add Task</button></div>`)}
const escapeText=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeState(v){if(typeof v==='string')return escapeText(v);if(Array.isArray(v))return v.map(safeState);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,safeState(x)]));return v}
async function api(path,data){const res=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-Hub-Request':'1'}:{},body:data?JSON.stringify(data):undefined,cache:'no-store'});const result=await res.json();if(!res.ok){if(res.status===401&&path!=='login'){S.viewer='';loginScreen()}throw Error(result.error||'Request failed')}return result}
async function loadProfiles(){try{const result=await api('profiles');S.profiles=safeState(result.profiles||{});if(!S.viewer)loginScreen()}catch{}}
let previous='', refreshing=false;
async function refresh(force=false){if(refreshing)return;refreshing=true;try{const state=await api('state');const raw=JSON.stringify(state);S=safeState(state);if(force||raw!==previous){previous=raw;const modal=document.getElementById('modal'),details=modal?.querySelector('.task-details');if(!modal)render(page);else if(details){const id=Number(details.dataset.taskId);modal.remove();if(taskById(id))openTaskDetails(id);else render(page)}}const el=document.getElementById('syncStatus');if(el)el.textContent='Synced just now'}catch(e){const el=document.getElementById('syncStatus');if(el)el.textContent='Connection lost · retrying';if(force&&S.viewer)alert(e.message)}finally{refreshing=false}}
let writing=false;
async function mutate(data,next=page){if(writing)return;writing=true;try{await api('action',data);document.getElementById('modal')?.remove();page=next;await refresh(true);return true}catch(e){alert(e.message);return false}finally{writing=false}}
const val=id=>document.getElementById(id).value.trim();
async function addTask(){const who=val('nw'),visibility=val('nv');if(visibility==='Assigned'&&!['Dad','Mom','Daughter'].includes(who)){alert('Choose a person for Assigned Person visibility.');return}const record={title:val('nt'),description:val('ndesc'),who,priority:val('np'),visibility,ack:document.getElementById('na').checked,dueDate:val('nd'),dueTime:val('ntime'),category:val('nc'),repeat:val('nr')};const result=await mutate(editingTaskId?{action:'edit',id:editingTaskId,record}:{action:'create',kind:'tasks',record},'tasks');if(result)editingTaskId=null;return result}
function openEditTask(id){const t=taskById(id);if(!t||!canManageTask(t))return;editingTaskId=id;openTaskForm();for(const [field,value] of Object.entries({nt:t.title,ndesc:t.description||'',nw:t.who||'',np:t.priority,nv:t.visibility,nc:t.category||'Other',nd:t.dueDate||'',ntime:t.dueTime||'',nr:t.repeat||'One Time'})){document.getElementById(field).value=value}const acknowledgement=document.getElementById('na');acknowledgement.checked=!!t.ack;acknowledgement.disabled=t.priority==='Urgent';document.querySelector('#modal h2').textContent='Edit Task';document.querySelector('#modal .actions .primary').textContent='Save Changes'}
function ack(id){return mutate({action:'ack',id})}
async function done(id){if(await mutate({action:'done',id})){const t=taskById(id);if(S.viewer==='Daughter'&&t?.category==='Home')celebrate()}}
function celebrate(){const d=document.createElement('div');d.className='celebrate';d.textContent='Done! ✅ Nice job! 🎉🌟';document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function openPost(){modal('<h2>📣 Share a family moment</h2><div class=field><label for=pt>Your update</label><textarea id=pt rows=4 maxlength=4000></textarea></div><button class="btn primary" onclick=addPost()>Post</button>')}
function addPost(){return mutate({action:'create',kind:'posts',record:{text:val('pt')}},'board')}
function react(id,emoji){return mutate({action:'react',id,emoji})}
function openAsk(){modal(`<h2>🙋 Ask ${displayName('Dad')} & ${displayName('Mom')}</h2><div class=field><label for=rt>Type</label><select id=rt><option>Permission</option><option>Purchase</option><option>Ride</option><option>Schedule Change</option><option>Question</option></select></div><div class=field><label for=rq>What would you like to ask?</label><textarea id=rq rows=4 maxlength=4000></textarea></div><button class="btn primary" onclick=addRequest()>Send request 💬</button>`)}
function addRequest(){return mutate({action:'create',kind:'requests',record:{text:val('rq'),type:val('rt')}},'ask')}
function requestAction(id,status){const reply=prompt('Add a note or conditions:','');if(reply!==null)mutate({action:'decision',id,status,reply},'requests')}
function loginScreen(){document.querySelector('#app').innerHTML=`<main class="shell login"><div class=hero><div class=emoji>🏡</div><h1>Martin-Riley<br>Family Hub</h1><p>A little less juggling.<br>A lot more together.</p></div><form class=card onsubmit="event.preventDefault();signIn()"><h2>Welcome home 💜</h2><div class=field><label for=loginName>Who is signing in?</label><select id=loginName>${['Dad','Mom','Daughter'].map(id=>`<option value="${id}">${displayName(id)}</option>`).join('')}</select></div><div class=field><label for=loginPassword>Your password</label><input id=loginPassword type=password autocomplete=current-password required></div><p id=loginError role=alert></p><button class="btn primary" id=loginButton>Come on in →</button><p class=meta>Private to our family. Each person has their own account.</p></form></main>`}
async function signIn(){const b=document.getElementById('loginButton');b.disabled=true;try{await api('login',{name:val('loginName'),password:document.getElementById('loginPassword').value});page='home';await refresh(true)}catch(e){document.getElementById('loginError').textContent=e.message;b.disabled=false}}
async function logout(){try{await api('logout',{});S={viewer:'',profiles:S.profiles};previous='';document.getElementById('modal')?.remove();loginScreen()}catch(e){alert(e.message)}}
function collection(which){const title={lists:'🛒 Shared Lists',vault:'🔒 Adult Vault',private:'💌 Me Only'}[which];if(which==='vault'&&!adult(S.viewer))return home();const items=which==='lists'?S.lists:S.notes.filter(n=>n.visibility===(which==='vault'?'Adults':'Me'));return `${renderTopBar()}<div class=hero><h1>${title}</h1><p>${which==='lists'?'Groceries, packing, and the little things.':which==='vault'?`A private space for ${displayName('Dad')} and ${displayName('Mom')}.`:'Just for you. Your family cannot see these items.'}</p></div><button class="btn primary" onclick="openItem('${which}')">+ Add item</button><div class=section></div>${items.map(n=>`<div class="card task"><div class=grow><b>${n.title||n.text}</b><p class=meta>${n.checked?'✅ Checked off':'○ Open'} · ${displayName(n.creator)}</p></div>${which==='lists'?`<button class=btn onclick="mutate({action:'check',id:${n.id}})">${n.checked?'Undo':'Check'}</button>`:''}${n.creator===S.viewer||adult(S.viewer)&&n.visibility!=='Me'?`<button class=btn aria-label="Delete item" onclick="if(confirm('Delete this item?'))mutate({action:'delete',id:${n.id}})">×</button>`:''}</div>`).join('')||'<div class=card>No items yet. Make this space yours ✨</div>'}`}
function openItem(which){const label={events:'calendar event',dance:'dance item',lists:'list item',private:'note',vault:'vault note'}[which]||'item';modal(`<h2>Add ${label}</h2><div class=field><label for=itemText>Details</label><textarea id=itemText maxlength=4000 required></textarea></div>${which==='events'?'<div class=field><label for=itemDate>Date and time</label><input id=itemDate type=datetime-local required></div>':''}${which==='dance'?'<div class=field><label for=itemCategory>Section</label><select id=itemCategory><option>Competitions</option><option>Schedule</option><option>Routines</option><option>Costumes</option><option>Checklists</option></select></div>':''}<button class="btn primary" onclick="createItem('${which}')">Save</button>`)}
function createItem(which){const record={text:val('itemText'),visibility:which==='vault'?'Adults':which==='private'?'Me':'Family'};if(which==='events'){record.date=val('itemDate');if(!record.date){alert('Choose a date and time');return}}if(which==='dance')record.category=val('itemCategory');return mutate({action:'create',kind:which==='vault'||which==='private'?'notes':which,record},which==='events'?'calendar':which)}
function calendar(){return `${renderTopBar()}<div class=section><h2>📅 Family Calendar</h2><button class=btn onclick="openItem('events')">+ Event</button></div>${[...S.events].sort((a,b)=>a.date.localeCompare(b.date)).map(e=>`<div class=card><b>${e.date.replace('T',' · ')}</b><p>${e.text}</p><div class=meta>${displayName(e.creator)}</div></div>`).join('')||'<div class=card>Your next family adventure starts here 🌷</div>'}`}
let danceTab='Competitions';
function dance(){return `${renderTopBar()}<div class=hero><h1>💃 Dance Hub</h1><p>Practice, sparkle, repeat ✨</p></div><div class=actions>${['Competitions','Schedule','Routines','Costumes','Checklists'].map(c=>`<button class="btn ${danceTab===c?'primary':''}" onclick="danceTab='${c}';render('dance')">${c==='Competitions'?'🏆 ':''}${c}</button>`).join('')}</div><div class=section><h2>${danceTab}</h2><button class=btn onclick="openItem('dance')">+ Add</button></div>${S.dance.filter(d=>d.category===danceTab).map(d=>`<div class="card task"><div class=grow>${d.text}</div><button class=btn onclick="mutate({action:'check',id:${d.id}})">${d.checked?'✅ Ready':'○ To do'}</button></div>`).join('')||'<div class=card>No details yet. Add schedules, venues, routines, or packing notes 🩰</div>'}`}
function tomorrow(){const tomorrowDate=(()=>{const d=new Date();d.setDate(d.getDate()+1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')})();return `${renderTopBar()}<div class=hero><h1>🌙 Ready for Tomorrow?</h1><p>Pack it, plan it, then relax.</p></div>${taskList(S.tasks.filter(t=>t.status==='open'&&(t.who===S.viewer||t.who==='Everyone')))}<div class=section><h2>Coming up</h2></div>${S.events.filter(e=>e.date.slice(0,10)===tomorrowDate).map(e=>`<div class=card>${e.text} · ${e.date.replace('T',' ')}</div>`).join('')||'<div class=card>No events scheduled tomorrow.</div>'}`}
function reminders(){return `${renderTopBar()}<div class=hero><h1>🔔 A gentle nudge</h1><p>Urgent tasks and upcoming family plans.</p></div>${taskList(S.tasks.filter(t=>t.status==='open'&&['Urgent','High','High Priority'].includes(t.priority)))}<div class=card>Reminders update while the app is open. Phone push notifications are not configured yet.</div>`}
function privacy(){return `${renderTopBar()}<div class=section><h2>🔐 Our family, our privacy</h2></div><div class=card><p>👨‍👩‍👧 Family: ${displayName('Dad')}, ${displayName('Mom')}, and ${displayName('Daughter')}</p><p>🔒 Adults Only: ${displayName('Dad')} and ${displayName('Mom')}</p><p>👤 Assigned Person: the selected family member</p><p>💌 Me Only: only the creator, including for parents</p><p class=meta>These rules are checked on the server before any data is sent to your phone. Activity history follows the same visibility.</p></div><div class=card><p>No location tracking. No ChatGPT integration or access has been configured.</p></div>`}
loginScreen();loadProfiles();refresh(true);setInterval(()=>{if(S.viewer&&document.visibilityState==='visible')refresh()},5000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&S.viewer)refresh()});document.addEventListener('change',e=>{if(e.target.id==='np'){const acknowledgement=document.getElementById('na');acknowledgement.disabled=e.target.value==='Urgent';if(acknowledgement.disabled)acknowledgement.checked=true}});
