// Remove V1 browser-only data; authenticated data is never persisted here.
localStorage.removeItem('mrhub');
let S={viewer:'',tasks:[],posts:[],requests:[],events:[],lists:[],dance:[],notes:[],activity:[],streak:0,points:0};const save=()=>{};const adult=v=>v==='Dad'||v==='Mom';const visible=t=>t.visibility==='Family'||(t.visibility==='Adults'&&adult(S.viewer))||(t.visibility==='Assigned'&&(t.who===S.viewer||t.who==='Everyone'))||(t.visibility==='Me'&&t.creator===S.viewer);function nav(){let daughter=S.viewer==='Daughter';return `<div class=nav><div class=navin>${[['home','🏠','Home'],['tasks','✅',daughter?'My Stuff':'Tasks'],['dance','💃','Dance'],[daughter?'ask':'board',daughter?'🙋':'📣',daughter?'Ask':'Board'],['family','👨‍👩‍👧','Family']].map(x=>`<button onclick="render('${x[0]}')" class="${page===x[0]?'active':''}"><span class=e>${x[1]}</span>${x[2]}</button>`).join('')}</div></div>`}let page='home';function top(){return `<div class=top><div><div class=brand>✨ Martin-Riley Family Hub</div><div class=sub>Our little corner of the world · <span id=syncStatus>Connected</span></div></div><button class=btn onclick="logout()">Sign out<br><small>${S.viewer}</small></button></div>`}
function home(){let d=S.viewer==='Daughter';return `${top()}<div class=hero><h1>${d?'🌈 Hey! Ready for a great day?':'☀️ Welcome back, '+S.viewer+'!'}</h1><div>${d?`🔥 ${S.streak}-day chore streak • 🏆 ${S.points} completed chores`:`${S.tasks.filter(t=>visible(t)&&t.status==='open').length} open items • ${S.requests.filter(r=>r.status==='Pending').length} request waiting`}</div></div><div class=grid>${(d?[['✅','My Stuff','tasks'],['💃','Dance','dance'],['🙋','Ask Mom & Dad','ask'],['📣','Family Board','board'],['📅','My Calendar','calendar'],['🌙','Tomorrow Prep','tomorrow'],['🛒','Shared Lists','lists'],['💌','Me Only','private'],['🔔','Reminders','reminders']]:[['🚨','Needs Attention','tasks'],['🙋','Requests','requests'],['📣','Family Board','board'],['📅','Calendar','calendar'],['💃','Dance Hub','dance'],['🌙','Tomorrow Prep','tomorrow'],['📊','Weekly Recap','recap'],['🔐','Privacy','privacy'],['🛒','Shared Lists','lists'],['🔒','Adult Vault','vault'],['💌','Me Only','private'],['🔔','Reminders','reminders']]).map(x=>`<button class="card tile" onclick="render('${x[2]}')"><span class=emoji>${x[0]}</span><b>${x[1]}</b></button>`).join('')}</div>${d?`<div class=card>🏅 ${S.points>=10?'Teamwork superstar':S.points>=1?'First win earned!':'Your first achievement is waiting'} · Complete chores to celebrate!</div><div class=section><h2>🌟 Family Chore Board</h2></div>${choreBoard()}`:`<div class=section><h2>Today</h2></div>${taskList(S.tasks.filter(t=>visible(t)&&t.status==='open').slice(0,4))}`}`}
function taskList(arr){return arr.map(t=>`<div class="card task"><div>${t.status==='done'?'✅':t.status==='missed'?'❌':'⏳'}</div><div class=grow><span class="pill ${t.priority==='Urgent'?'urgent':t.priority==='High'?'high':t.priority==='Important'?'important':''}">${t.priority==='Urgent'?'🚨':t.priority==='High'?'🔴':t.priority==='Important'?'⭐':'•'} ${t.priority}</span><h3>${t.title}</h3><div class=meta>${t.who} • ${t.visibility}${t.reason?' • “'+t.reason+'”':''}</div><div class=actions>${t.ack&&t.status==='open'&&!t.acked.includes(S.viewer)&& (t.who===S.viewer||t.who==='Everyone')?`<button class="btn primary" onclick="ack(${t.id})">Acknowledge</button>`:''}${(t.who===S.viewer||t.who==='Everyone')&&t.status==='open'?`<button class="btn good" onclick="done(${t.id})">Complete</button><button class="btn bad" onclick="miss(${t.id})">Not complete</button>`:''}</div></div></div>`).join('')||'<div class=card>🎉 Nothing here right now.</div>'}
function choreBoard(){return taskList(S.tasks.filter(t=>t.visibility==='Family'))}function tasks(){return `${top()}<div class=section><h2>${S.viewer==='Daughter'?'✅ My Stuff':'✅ Tasks & Chores'}</h2></div>${taskList(S.tasks.filter(t=>visible(t)))}${adult(S.viewer)?'<button class=fab onclick="openAdd()">+</button>':''}`}
function board(){return `${top()}<div class=section><h2>📣 Family Bulletin Board</h2><button class=btn onclick=openPost()>+ Post</button></div>${S.posts.map(p=>`<div class="card boardpost"><b>${p.by==='Dad'?'👨':p.by==='Mom'?'👩':'👧'} ${p.by}</b><p>${p.text}</p><div class=reactions>${['❤️','👍','😂','🎉'].map(e=>`<button class=reaction onclick="react(${p.id},'${e}')">${e} ${p.reacts[e]||0}</button>`).join('')}</div></div>`).join('')}`}
function ask(){return `${top()}<div class=hero><h1>🙋 Ask Mom & Dad</h1><div>Need permission, a ride, or have a question? Ask us here! 💬</div></div><button class="btn primary" onclick=openAsk()>+ New Request</button><div class=section><h2>My Requests</h2></div>${S.requests.map(r=>`<div class=card><b>${r.type}</b><p>${r.text}</p><div class="status ${r.status.toLowerCase()}">${r.status==='Pending'?'🟡':r.status==='Approved'?'🟢':'🔴'} ${r.status}</div>${r.reply?`<p class=meta>Parent: ${r.reply}</p>`:''}</div>`).join('')}`}
function requests(){return `${top()}<div class=section><h2>🙋 Parent Requests Inbox</h2></div>${S.requests.map(r=>`<div class=card><b>${r.type}</b><p>${r.text}</p><div class="status ${r.status.toLowerCase()}">${r.status}</div>${r.status==='Pending'?`<div class=actions><button class="btn good" onclick="requestAction(${r.id},'Approved')">✅ Approve</button><button class="btn bad" onclick="requestAction(${r.id},'Denied')">❌ Deny</button></div>`:''}${r.reply?`<p class=meta>${r.reply}</p>`:''}</div>`).join('')}`}
function dance(){return `${top()}<div class=hero><h1>💃 Dance Hub</h1><div>Everything dance, all in one place ✨</div></div><div class=grid>${[['🏠','Dance Home'],['📅','Schedule'],['🩰','Routines'],['🏆','Competitions'],['👗','Costumes'],['✅','Checklists']].map(x=>`<div class="card tile"><span class=emoji>${x[0]}</span><b>${x[1]}</b>${x[1]==='Competitions'?'<div class=meta>Saturday • Schedule Pending ⏳</div>':''}</div>`).join('')}</div>`}
function calendar(){return `${top()}<div class=section><h2>📅 Family Calendar</h2></div>${S.events.map(e=>`<div class=card style="margin-bottom:10px"><b>${e.date}</b><p>${e.text}</p></div>`).join('')}`}
function tomorrow(){return `${top()}<div class=hero><h1>🌙 Ready for Tomorrow?</h1><div>Pack it, plan it, then relax ✨</div></div>${taskList(S.tasks.filter(t=>visible(t)&&t.status==='open').slice(0,3))}<div class=card><b>📅 Tomorrow</b><p>💃 Dance practice • 5:30 PM</p><p>🎒 School day</p></div>`}
function recap(){const since=new Date(Date.now()-7*86400000).toISOString();const completed=S.tasks.filter(t=>t.status==='done'&&t.completedAt>=since).length;return `${top()}<div class=hero><h1>📊 Our Week 🎉</h1><div>Nice teamwork, Martin-Riley family!</div></div><div class=grid><div class=card><div class=emoji>🔥</div><b>${S.streak} day streak</b></div><div class=card><div class=emoji>✅</div><b>${completed} completed in 7 days</b></div><div class=card><div class=emoji>🙋</div><b>${S.requests.filter(r=>r.status==='Approved').length} approved requests total</b></div><div class=card><div class=emoji>🎉</div><b>${S.posts.filter(p=>p.createdAt>=since).length} posts in 7 days</b></div></div>`}
function family(){return `${top()}<div class=section><h2>👨‍👩‍👧 Family</h2></div>${['Dad','Mom','Daughter'].map(n=>`<div class="card task"><div class=avatar>${n==='Dad'?'👨':n==='Mom'?'👩':'👧'}</div><div><b>${n}</b><div class=meta>${n==='Daughter'?'Family Member • 🔥 '+S.streak+' day streak':'Adult / Admin'}</div></div></div>`).join('')}<div class=section><h2>Recent Activity</h2></div>${S.activity.slice(0,8).map(a=>`<div class=card style="margin-bottom:8px">${a}</div>`).join('')}`}
function privacy(){return `${top()}<div class=section><h2>🔐 Access & Privacy</h2></div><div class=card><b>🤖 ChatGPT default access</b><p>Tasks: Limited read-only</p><p>Family Calendar: Limited read-only</p><p>🔒 Me Only: Blocked</p><p>🔒 Adult Vault: Blocked</p><p>📍 Location: Blocked</p><p>💵 Financial information: Blocked</p></div><div class=card style="margin-top:12px"><b>Visibility rules</b><p>👨‍👩‍👧 Family • 🔒 Adults Only • 👤 Assigned Person • 🔐 Me Only</p></div>`}
function render(p='home'){if(!S.viewer){loginScreen();return}page=p;let fn={home,tasks,board,ask,requests,dance,calendar,tomorrow,recap,family,privacy,lists:()=>collection('lists'),vault:()=>collection('vault'),private:()=>collection('private'),reminders}[p]||home;document.querySelector('#app').innerHTML=`<main class=shell>${fn()}</main>${nav()}`;window.scrollTo(0,0)}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class=modal id=modal onclick="if(event.target===this)this.remove()"><div class=sheet role=dialog aria-modal=true><button class="btn close-sheet" aria-label="Close" onclick="document.getElementById('modal').remove();render(page)">×</button>${html}</div></div>`)}function openAdd(){modal(`<h2>✨ Add Task</h2><div class=field><label>Task</label><input id=nt></div><div class=row><div class=field><label>Assign</label><select id=nw><option>Dad</option><option>Mom</option><option>Daughter</option><option>Everyone</option></select></div><div class=field><label>Priority</label><select id=np onchange="document.querySelector('#na').checked=this.value==='Urgent'"><option>Normal</option><option>Important</option><option>High</option><option>Urgent</option></select></div></div><div class=field><label>Visibility</label><select id=nv><option>Family</option><option>Adults</option><option>Assigned</option><option>Me</option></select></div><label><input type=checkbox id=na> Require acknowledgement (Urgent always requires it)</label><div class=actions><button class="btn primary" onclick=addTask()>Add Task</button></div>`)}
const escapeText=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeState(v){if(typeof v==='string')return escapeText(v);if(Array.isArray(v))return v.map(safeState);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,safeState(x)]));return v}
async function api(path,data){const res=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-Hub-Request':'1'}:{},body:data?JSON.stringify(data):undefined,cache:'no-store'});const result=await res.json();if(!res.ok){if(res.status===401&&path!=='login'){S.viewer='';loginScreen()}throw Error(result.error||'Request failed')}return result}
let previous='', refreshing=false;
async function refresh(force=false){if(refreshing)return;refreshing=true;try{const state=await api('state');const raw=JSON.stringify(state);S=safeState(state);if(force||raw!==previous){previous=raw;if(!document.getElementById('modal'))render(page)}const el=document.getElementById('syncStatus');if(el)el.textContent='Synced just now'}catch(e){const el=document.getElementById('syncStatus');if(el)el.textContent='Connection lost · retrying';if(force&&S.viewer)alert(e.message)}finally{refreshing=false}}
let writing=false;
async function mutate(data,next=page){if(writing)return;writing=true;try{await api('action',data);document.getElementById('modal')?.remove();page=next;await refresh(true);return true}catch(e){alert(e.message);return false}finally{writing=false}}
const val=id=>document.getElementById(id).value.trim();
function addTask(){return mutate({action:'create',kind:'tasks',record:{title:val('nt'),who:val('nw'),priority:val('np'),visibility:val('nv'),ack:document.getElementById('na').checked}},'tasks')}
function ack(id){return mutate({action:'ack',id})}
async function done(id){if(await mutate({action:'done',id}))celebrate()}
function miss(id){const reason=prompt('What got in the way?');if(reason!==null)mutate({action:'miss',id,reason})}
function celebrate(){const d=document.createElement('div');d.className='celebrate';d.textContent='🎉🌟';document.body.appendChild(d);setTimeout(()=>d.remove(),1400)}
function openPost(){modal('<h2>📣 Share a family moment</h2><div class=field><label for=pt>Your update</label><textarea id=pt rows=4 maxlength=4000></textarea></div><button class="btn primary" onclick=addPost()>Post</button>')}
function addPost(){return mutate({action:'create',kind:'posts',record:{text:val('pt')}},'board')}
function react(id,emoji){return mutate({action:'react',id,emoji})}
function openAsk(){modal('<h2>🙋 Ask Mom & Dad</h2><div class=field><label for=rt>Type</label><select id=rt><option>Permission</option><option>Purchase</option><option>Ride</option><option>Schedule Change</option><option>Question</option></select></div><div class=field><label for=rq>What would you like to ask?</label><textarea id=rq rows=4 maxlength=4000></textarea></div><button class="btn primary" onclick=addRequest()>Send request 💬</button>')}
function addRequest(){return mutate({action:'create',kind:'requests',record:{text:val('rq'),type:val('rt')}},'ask')}
function requestAction(id,status){const reply=prompt('Add a note or conditions:','');if(reply!==null)mutate({action:'decision',id,status,reply},'requests')}
function loginScreen(){document.querySelector('#app').innerHTML=`<main class="shell login"><div class=hero><div class=emoji>🏡</div><h1>Martin-Riley<br>Family Hub</h1><p>A little less juggling.<br>A lot more together.</p></div><form class=card onsubmit="event.preventDefault();signIn()"><h2>Welcome home 💜</h2><div class=field><label for=loginName>Who is signing in?</label><select id=loginName><option>Dad</option><option>Mom</option><option>Daughter</option></select></div><div class=field><label for=loginPassword>Your password</label><input id=loginPassword type=password autocomplete=current-password required></div><p id=loginError role=alert></p><button class="btn primary" id=loginButton>Come on in →</button><p class=meta>Private to our family. Each person has their own account.</p></form></main>`}
async function signIn(){const b=document.getElementById('loginButton');b.disabled=true;try{await api('login',{name:val('loginName'),password:document.getElementById('loginPassword').value});page='home';await refresh(true)}catch(e){document.getElementById('loginError').textContent=e.message;b.disabled=false}}
async function logout(){try{await api('logout',{});S={viewer:''};previous='';document.getElementById('modal')?.remove();loginScreen()}catch(e){alert(e.message)}}
function collection(which){const title={lists:'🛒 Shared Lists',vault:'🔒 Adult Vault',private:'💌 Me Only'}[which];if(which==='vault'&&!adult(S.viewer))return home();const items=which==='lists'?S.lists:S.notes.filter(n=>n.visibility===(which==='vault'?'Adults':'Me'));return `${top()}<div class=hero><h1>${title}</h1><p>${which==='lists'?'Groceries, packing, and the little things.':which==='vault'?'A private space for Mom and Dad.':'Just for you. Your family cannot see these items.'}</p></div><button class="btn primary" onclick="openItem('${which}')">+ Add item</button><div class=section></div>${items.map(n=>`<div class="card task"><div class=grow><b>${n.title||n.text}</b><p class=meta>${n.checked?'✅ Checked off':'○ Open'} · ${n.creator}</p></div>${which==='lists'?`<button class=btn onclick="mutate({action:'check',id:${n.id}})">${n.checked?'Undo':'Check'}</button>`:''}${n.creator===S.viewer||adult(S.viewer)&&n.visibility!=='Me'?`<button class=btn aria-label="Delete item" onclick="if(confirm('Delete this item?'))mutate({action:'delete',id:${n.id}})">×</button>`:''}</div>`).join('')||'<div class=card>No items yet. Make this space yours ✨</div>'}`}
function openItem(which){modal(`<h2>Add ${which==='events'?'calendar event':which==='dance'?'dance item':'item'}</h2><div class=field><label for=itemText>Details</label><textarea id=itemText maxlength=4000 required></textarea></div>${which==='events'?'<div class=field><label for=itemDate>Date and time</label><input id=itemDate type=datetime-local required></div>':''}${which==='dance'?'<div class=field><label for=itemCategory>Section</label><select id=itemCategory><option>Competitions</option><option>Schedule</option><option>Routines</option><option>Costumes</option><option>Checklists</option></select></div>':''}<button class="btn primary" onclick="createItem('${which}')">Save</button>`)}
function createItem(which){const record={text:val('itemText'),visibility:which==='vault'?'Adults':which==='private'?'Me':'Family'};if(which==='events'){record.date=val('itemDate');if(!record.date){alert('Choose a date and time');return}}if(which==='dance')record.category=val('itemCategory');return mutate({action:'create',kind:which==='vault'||which==='private'?'notes':which,record},which==='events'?'calendar':which)}
function calendar(){return `${top()}<div class=section><h2>📅 Family Calendar</h2><button class=btn onclick="openItem('events')">+ Event</button></div>${[...S.events].sort((a,b)=>a.date.localeCompare(b.date)).map(e=>`<div class=card><b>${e.date.replace('T',' · ')}</b><p>${e.text}</p></div>`).join('')||'<div class=card>Your next family adventure starts here 🌷</div>'}`}
let danceTab='Competitions';
function dance(){return `${top()}<div class=hero><h1>💃 Dance Hub</h1><p>Practice, sparkle, repeat ✨</p></div><div class=actions>${['Competitions','Schedule','Routines','Costumes','Checklists'].map(c=>`<button class="btn ${danceTab===c?'primary':''}" onclick="danceTab='${c}';render('dance')">${c==='Competitions'?'🏆 ':''}${c}</button>`).join('')}</div><div class=section><h2>${danceTab}</h2><button class=btn onclick="openItem('dance')">+ Add</button></div>${S.dance.filter(d=>d.category===danceTab).map(d=>`<div class="card task"><div class=grow>${d.text}</div><button class=btn onclick="mutate({action:'check',id:${d.id}})">${d.checked?'✅ Ready':'○ To do'}</button></div>`).join('')||'<div class=card>No details yet. Add schedules, venues, routines, or packing notes 🩰</div>'}`}
function tomorrow(){const tomorrowDate=(()=>{const d=new Date();d.setDate(d.getDate()+1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')})();return `${top()}<div class=hero><h1>🌙 Ready for Tomorrow?</h1><p>Pack it, plan it, then relax.</p></div>${taskList(S.tasks.filter(t=>t.status==='open'&&(t.who===S.viewer||t.who==='Everyone')))}<div class=section><h2>Coming up</h2></div>${S.events.filter(e=>e.date.slice(0,10)===tomorrowDate).map(e=>`<div class=card>${e.text} · ${e.date.replace('T',' ')}</div>`).join('')||'<div class=card>No events scheduled tomorrow.</div>'}`}
function reminders(){return `${top()}<div class=hero><h1>🔔 A gentle nudge</h1><p>Urgent tasks and upcoming family plans.</p></div>${taskList(S.tasks.filter(t=>t.status==='open'&&['Urgent','High'].includes(t.priority)))}<div class=card>Reminders update while the app is open. Phone push notifications are not configured yet.</div>`}
function privacy(){return `${top()}<div class=section><h2>🔐 Our family, our privacy</h2></div><div class=card><p>👨‍👩‍👧 Family: all three accounts</p><p>🔒 Adults Only: Mom and Dad</p><p>👤 Assigned Person: only the selected person</p><p>💌 Me Only: only the creator, including for parents</p><p class=meta>These rules are checked on the server before any data is sent to your phone. Activity history follows the same visibility.</p></div><div class=card><p>No location tracking. No ChatGPT integration or access has been configured.</p></div>`}
loginScreen();refresh(true);setInterval(()=>{if(S.viewer&&document.visibilityState==='visible')refresh()},5000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&S.viewer)refresh()});
