const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const app={innerHTML:'',modal:''};
const context=vm.createContext({
 document:{querySelector:()=>app,getElementById:()=>null,body:{insertAdjacentHTML:(_position,html)=>{app.modal=html}},addEventListener(){},visibilityState:'visible'},
 window:{scrollTo(){}},localStorage:{removeItem(){}},
 fetch:()=>new Promise(()=>{}),setInterval(){},setTimeout(){},console,
 alert(){},prompt(){return null},confirm(){return false}
});
vm.runInContext(fs.readFileSync('app.js','utf8'),context);
assert.match(app.innerHTML,/Welcome home/);
vm.runInContext("S.profiles={Dad:{displayName:'Jermaine',role:'ADMIN'},Mom:{displayName:'Stephanie',role:'ADMIN'},Daughter:{displayName:'Arielle',role:'CHILD'}};loginScreen()",context);
assert.match(app.innerHTML,/value="Dad">Jermaine/);
assert.match(app.innerHTML,/value="Mom">Stephanie/);
assert.match(app.innerHTML,/value="Daughter">Arielle/);
assert.doesNotMatch(app.innerHTML,/Maddox/);
vm.runInContext("S={viewer:'Dad',tasks:[],posts:[],requests:[],events:[],lists:[],dance:[],notes:[],activity:[],streak:0,points:0}",context);
vm.runInContext("S.profiles={Dad:{displayName:'Jermaine',role:'ADMIN'},Mom:{displayName:'Stephanie',role:'ADMIN'},Daughter:{displayName:'Arielle',role:'CHILD'}}",context);
for(const role of ['Dad','Mom','Daughter']){
 vm.runInContext("S.viewer='"+role+"'",context);
 for(const page of ['home','tasks','board','ask','requests','dance','calendar','tomorrow','recap','family','privacy','lists','private','vault','reminders']){
  vm.runInContext("render('"+page+"')",context);
  assert.match(app.innerHTML,/Martin-Riley Family Hub/);
  assert.doesNotMatch(app.innerHTML,/undefined|NaN/);
 }
}
vm.runInContext("S.familyMembers={Dad:{memberId:'Dad',displayName:'Jermaine',profileType:'account',hasAccount:true},Mom:{memberId:'Mom',displayName:'Stephanie',profileType:'account',hasAccount:true},Daughter:{memberId:'Daughter',displayName:'Arielle',profileType:'account',hasAccount:true},Maddox:{memberId:'Maddox',displayName:'Maddox',profileType:'managed_child',role:'MANAGED CHILD PROFILE',hasAccount:false,managedBy:['Dad','Mom'],avatar:'⚾'},ManagedChildTwo:{memberId:'ManagedChildTwo',displayName:'Future Child',profileType:'managed_child',role:'MANAGED CHILD PROFILE',hasAccount:false,managedBy:['Dad','Mom'],avatar:'🏀'}};const managedDate=dateFromKey(hubToday());managedDate.setDate(managedDate.getDate()+1);S.managedTomorrow=dateKey(managedDate);S.activities=[{id:801,memberId:'Maddox',activityName:'Baseball Practice',activityType:'Baseball',eventType:'Practice',organization:'Little League',season:'Fall 2026',date:S.managedTomorrow,startTime:'17:30',endTime:'18:30',location:'North Field',equipmentNotes:'Bring glove, cleats and water bottle',parentNotes:'Arrive early',creator:'Dad'},{id:804,memberId:'ManagedChildTwo',activityName:'Future camp',activityType:'Camp',eventType:'Camp',date:S.managedTomorrow,creator:'Mom'}];S.events=[{id:802,title:'Maddox · Baseball Practice',date:S.managedTomorrow,startTime:'17:30',endTime:'18:30',location:'North Field',description:'Bring glove, cleats and water bottle',category:'Family',visibility:'Family',who:'Everyone',people:['Dad','Mom','Daughter','Maddox'],sourceActivityId:801}];S.tasks=[{id:803,title:'Pack Maddox glove',who:'Maddox',visibility:'Family',status:'open',creator:'Dad',ack:false,chore:false,category:'Home'}];S.viewer='Dad';render('family')",context);
for(const text of ['Maddox','Managed Child Profile','No login or device','Baseball Practice','Little League','North Field','Bring glove, cleats and water bottle']) assert.ok(app.innerHTML.includes(text),text);
for(const structure of ['maddox-activity-content','maddox-activity-kind','maddox-activity-date','maddox-activity-location','maddox-activity-equipment']) assert.ok(app.innerHTML.includes(structure),structure);
assert.ok(app.innerHTML.includes('Future Child')&&app.innerHTML.includes('Future camp'));
assert.ok(!app.innerHTML.includes('username')&&!app.innerHTML.includes('password'));
vm.runInContext("openManagedProfileActivity('Maddox')",context);
assert.ok(app.modal.includes('<select id="managed-Maddox-type">')&&app.modal.includes('</select>'));
assert.doesNotMatch(app.modal,/<textarea id="managed-Maddox-type"/);
for(const itemType of ['Practice','Game / Event','School Activity','Camp','Other']) assert.ok(app.modal.includes(`<option ${itemType==='Practice'?'selected':''}>${itemType}</option>`),itemType);
vm.runInContext("render('tomorrow')",context);
assert.ok(app.innerHTML.includes('Maddox · Baseball Practice')&&app.innerHTML.includes('Bring glove, cleats and water bottle'));
vm.runInContext("render('tasks')",context);
assert.ok(app.innerHTML.includes('Maddox · managed profile'));
assert.ok(app.innerHTML.includes('Mark managed item complete')&&!app.innerHTML.includes('Acknowledge'));
assert.ok(app.innerHTML.includes('Mark managed item complete')&&!app.innerHTML.includes('Acknowledge'));
vm.runInContext("S.viewer='Daughter';render('family')",context);
assert.ok(app.innerHTML.includes('Baseball Practice')&&!app.innerHTML.includes('Delete activity')&&!app.innerHTML.includes('Arrive early'));
vm.runInContext("render('tasks')",context);
assert.ok(!app.innerHTML.includes('Mark managed item complete'));
vm.runInContext("S.viewer='Dad';render('privacy')",context);
assert.ok(app.innerHTML.includes('Maddox')&&app.innerHTML.includes('Managed Child Profile · No Account'));
vm.runInContext("S.viewer='Daughter';render('privacy')",context);
assert.ok(!app.innerHTML.includes('Area access'));
const taskAssigneeSelect={};
taskAssigneeSelect.addEventListener=()=>{};
taskAssigneeSelect.insertAdjacentHTML=(_position,html)=>{app.modal=app.modal.replace('</select>',html+'</select>')};
context.document.getElementById=id=>id==='nw'?taskAssigneeSelect:null;
vm.runInContext("S.viewer='Dad';render('tasks');openAdd()",context);
assert.ok(app.modal.includes('Maddox · parent-managed'));
vm.runInContext("S.viewer='Dad';render('tasks');openAdd()",context);
for(const field of ['id=nt','id=ndesc','id=nw','id=np','id=nv','id=nd','id=ntime','id=nc','id=nr','id=nInterval','id=na']) assert.ok(app.modal.includes(field),field);
for(const choice of ['Jermaine','Stephanie','Arielle','Everyone','Unassigned','High Priority','Weekdays','Appointments']) assert.ok(app.modal.includes(choice),choice);
vm.runInContext("S.viewer='Dad';render('home')",context);
for(const action of ['+ Task','+ Event','+ List Item','+ Note']) assert.ok(app.innerHTML.includes(action),action);
vm.runInContext("S.activity=[{summary:'✅ Arielle completed \\\"Take out trash\\\"',createdAt:'2026-10-02T00:02:00Z'}];render('home')",context);
assert.ok(app.innerHTML.includes('Recent Activity')&&app.innerHTML.includes('Arielle completed'));
vm.runInContext("S.viewer='Daughter';render('home')",context);
assert.ok(app.innerHTML.includes('Weekly Recap'));
vm.runInContext("S.badgeCounts={tasks:12,dance:1,requests:2,board:3,calendar:1,recap:1,lists:1,reminders:2,recognition:1};render('home')",context);
assert.ok(app.innerHTML.includes('9+'));
for(const label of ['My Stuff','Dance','Family Board','Weekly Recap','Shared Lists','Reminders']) assert.ok(app.innerHTML.includes(label),label);
assert.ok(app.innerHTML.includes('Ask Jermaine &amp; Stephanie')||app.innerHTML.includes('Ask Jermaine & Stephanie'));
assert.ok(app.innerHTML.includes('aria-label="2 notifications">2</span>'));
const renderedNav=app.innerHTML.match(/<div class=nav>[\s\S]*?<\/div><\/div>/)?.[0]||'';
assert.ok(renderedNav.includes('notification-badge'));
assert.ok(renderedNav.includes('>Family<span class=notification-badge'));
vm.runInContext("S.viewer='Dad';render('home')",context);
const parentNav=app.innerHTML.match(/<div class=nav>[\s\S]*?<\/div><\/div>/)?.[0]||'';
assert.ok(app.innerHTML.includes('Requests')&&parentNav.includes('notification-badge'));
for(const group of ['Today & Attention','Family & Dance','Private & Review']) assert.ok(app.innerHTML.includes(group),group);
for(const route of ["render('vault')","render('private')","render('privacy')","render('recap')"]) assert.ok(app.innerHTML.includes(route),route);
vm.runInContext("S.viewer='Daughter';render('home')",context);
assert.ok(!app.innerHTML.includes('Adult Vault'));
vm.runInContext("S.notes=[{id:801,space:'Vault',visibility:'Adults',title:'Insurance details',category:'Insurance',notes:'Policy contact',creator:'Dad',createdAt:'2026-10-02T12:00:00Z'},{id:802,space:'Me',visibility:'Me',title:'Dad personal thought',category:'Idea',notes:'Private to dad',creator:'Dad',createdAt:'2026-10-02T12:00:00Z'},{id:803,space:'Me',visibility:'Me',title:'Mom personal thought',category:'Idea',notes:'Private to mom',creator:'Mom',createdAt:'2026-10-02T12:00:00Z'}];S.badgeCounts.vault=2;S.badgeCounts.private=1",context);
vm.runInContext("render('vault')",context);
assert.ok(!app.innerHTML.includes('Insurance details'));
vm.runInContext("render('private')",context);
assert.ok(!app.innerHTML.includes('Dad personal thought')&&!app.innerHTML.includes('Mom personal thought'));
vm.runInContext("S.viewer='Dad';render('vault')",context);
for(const text of ['Insurance details','Policy contact','not a password manager','full Social Security numbers','Bills / Financial Notes']) assert.ok(app.innerHTML.toLowerCase().includes(text.toLowerCase()),text);
vm.runInContext("openPrivateNote('vault')",context);
for(const field of ['privateTitle','privateCategory','privateNotes','privateDate','privateReminderDate','Save entry']) assert.ok(app.modal.includes(field),field);
assert.ok(app.modal.includes('passwords')&&app.modal.includes('authentication secrets'));
vm.runInContext("S.viewer='Mom';render('vault')",context);
assert.ok(app.innerHTML.includes('Insurance details'));
vm.runInContext("S.viewer='Dad';S.badgeCounts.vault=1;S.badgeCounts.private=1;render('private')",context);
assert.ok(app.innerHTML.includes('Jermaine')||app.innerHTML.includes('Dad'));
vm.runInContext("render('privacy')",context);
for(const text of ['Access & Privacy','Adult / Admin','Child / Family Member','Family Calendar','Tasks / Chores','Adult Vault','Me Only','Financial / Dance financial information','ChatGPT Access','read-only','Blocked']) assert.ok(app.innerHTML.includes(text),text);
for(const secret of ['Insurance details','Policy contact','Dad personal thought','Mom personal thought']) assert.ok(!app.innerHTML.includes(secret),secret);
vm.runInContext("S.viewer='Daughter';render('privacy')",context);
assert.ok(!app.innerHTML.includes('Area access')&&!app.innerHTML.includes('Shared Adult Vault'));
vm.runInContext("render('ask')",context);
assert.ok(!app.innerHTML.includes('+ Task'));
assert.ok(app.innerHTML.includes('Ask Jermaine &amp; Stephanie')||app.innerHTML.includes('Ask Jermaine & Stephanie'));
vm.runInContext("openAsk()",context);
for(const field of ['id=rt','id=rq','id=requestDate','id=requestTime','id=requestDetails']) assert.ok(app.modal.includes(field),field);
for(const type of ['Permission','Purchase','Ride','Sleepover/Friend','Schedule Change','Chore/Task','Question','Other']) assert.ok(app.modal.includes(type),type);
vm.runInContext("S.requests=[{id:1,creator:'Daughter',type:'Permission',title:'Friends house',text:'Can I go?',date:'2026-10-12',time:'18:30',description:'Maya’s parent is driving.',status:'Pending',responses:[{by:'Dad',status:'Message',reply:'Which friend?',createdAt:'2026-10-02T12:00:00Z'}]}];render('ask')",context);
for(const text of ['Friends house','2026','18:30','Maya’s parent is driving.','Jermaine','Which friend?']) assert.ok(app.innerHTML.includes(text),text);
vm.runInContext("S.viewer='Dad';render('requests')",context);
for(const action of ['Approve','Deny','Ask a Question / Reply']) assert.ok(app.innerHTML.includes(action),action);
vm.runInContext("requestAction(1,'Approved')",context);
assert.ok(app.modal.includes('Optional note / conditions')&&app.modal.includes('id=requestAddCalendar type=checkbox'));
vm.runInContext("S.viewer='Dad';S.activity=['Jermaine created a task'];render('family')",context);
assert.ok(app.innerHTML.includes('Jermaine')&&app.innerHTML.includes('Stephanie')&&app.innerHTML.includes('Arielle'));
vm.runInContext("S.viewer='Dad';taskFilterState.status='All';S.tasks=[{id:41,title:'Take out trash',description:'Blue bin',who:'Daughter',creator:'Dad',priority:'Urgent',visibility:'Family',category:'Home',dueDate:'2026-10-03',dueTime:'12:02',repeat:'Weekly',ack:true,acked:['Daughter'],acknowledgements:[{person:'Daughter',acknowledgedAt:'2026-10-02T00:00:00Z'}],status:'done',completedBy:'Daughter',completedAt:'2026-10-02T00:02:00Z',createdAt:'2026-10-01T12:00:00Z',updatedAt:'2026-10-02T00:02:00Z',updatedBy:'Daughter',completionHistory:[{completedBy:'Daughter',completedAt:'2026-10-02T00:02:00Z'}]}];render('tasks');openTaskDetails(41)",context);
for(const text of ['role=button','Completed by','Edit / Reassign','Reopen','Delete','Acknowledged by','Completion history','Last updated','Completion status']) assert.ok((text==='role=button'?app.innerHTML:app.modal).includes(text),text);
vm.runInContext("confirmDeleteTask(41)",context);
assert.ok(app.modal.includes('Delete “Take out trash”?')&&app.modal.includes('Delete Task')&&app.modal.includes('Cancel'));
vm.runInContext("S.viewer='Dad';S.tasks=[{id:43,title:'Pack dance bag',who:'Daughter',creator:'Dad',priority:'Normal',visibility:'Family',category:'Home',repeat:'One Time',ack:true,acked:['Daughter'],status:'open'}];openTaskDetails(43)",context);
assert.ok(app.modal.includes('Mark Complete')&&app.modal.includes('Mark Not Complete'));
vm.runInContext("S.viewer='Daughter';S.tasks=[{id:42,title:'Pack dance bag',description:'',who:'Daughter',creator:'Dad',priority:'Normal',visibility:'Family',category:'Home',repeat:'One Time',ack:false,acked:[],status:'open',createdAt:'2026-10-01T12:00:00Z'}];openTaskDetails(42)",context);
assert.ok(!app.modal.includes('Edit / Reassign')&&!app.modal.includes('Delete Task'));
vm.runInContext("openMissReason(42,false)",context);
for(const reason of ['Ran out of time','Waiting on someone/something','Rescheduled','No longer needed','Other']) assert.ok(app.modal.includes(reason),reason);
vm.runInContext("S.viewer='Dad';render('tasks')",context);
for(const filter of ['Status','Assigned','Priority','Category','Completed','Not Completed']) assert.ok(app.innerHTML.includes(filter),filter);
vm.runInContext("S.viewer='Daughter';S.tasks=[{id:44,title:'Arielle chore',who:'Daughter',creator:'Dad',priority:'Normal',visibility:'Family',category:'Home',ack:false,acked:[],status:'open'}];render('tasks')",context);
assert.ok(!app.innerHTML.includes('task-filters')&&app.innerHTML.includes('task-card')&&app.innerHTML.includes('Arielle chore'));
vm.runInContext("S.viewer='Dad';render('calendar')",context);
for(const control of ['Month','Agenda','Today','Previous month','Next month']) assert.ok(app.innerHTML.includes(control),control);
vm.runInContext("S.viewer='Daughter';render('calendar')",context);
assert.ok(!app.innerHTML.includes('+ Event'));
vm.runInContext("S.viewer='Dad';S.events=[];S.dance=[];S.activities=[];S.tasks=[];S.reminders=[];render('reminders');render('tomorrow')",context);
assert.ok(app.innerHTML.includes('What do we need to be ready for tomorrow?'));
assert.ok(!app.innerHTML.includes("Tomorrow's Schedule")&&!app.innerHTML.includes('Things To Do'));
vm.runInContext("const prepDate=dateFromKey(hubToday());prepDate.setDate(prepDate.getDate()+1);S.prepDate=dateKey(prepDate);S.dance=[{id:101,title:'Spring Showcase',danceType:'competition',startDate:S.prepDate,endDate:S.prepDate,schedulePending:true,deadlines:[{id:'fee',title:'Fee due',date:S.prepDate}],fees:[{label:'Entry fee',amount:125}],routineIds:[102],costumeIds:[103]},{id:102,title:'Moonlight',danceType:'routine',routineType:'Solo',competitionIds:[101],choreographer:'Ms. Lee',costumeId:103},{id:103,title:'Moonlight costume',danceType:'costume',routineIds:[102],ordered:true,received:false,alterationsNeeded:true,alterationsCompleted:false,neededBy:S.prepDate},{id:104,title:'Packing list',danceType:'checklist',checklistType:'Competition Packing',competitionId:101,checklistItems:[{id:1,text:'Shoes',checked:false}]},{id:105,title:'Studio practice',danceType:'schedule',date:S.prepDate,time:'17:30'}];S.events=[{id:201,title:'School concert',date:S.prepDate,category:'School',visibility:'Family',who:'Everyone',allDay:true},{id:202,title:'Dance practice',date:S.prepDate,startTime:'17:30',category:'Dance',visibility:'Family',who:'Daughter'}];S.tasks=[{id:301,title:'Pack water bottle',status:'open',dueDate:S.prepDate,category:'Home',who:'Daughter',visibility:'Family',creator:'Dad',chore:true},{id:302,title:'Dad private task',status:'open',dueDate:S.prepDate,category:'Home',who:'Dad',visibility:'Me',creator:'Dad'}];S.reminders=[{id:1,title:'Remember shoes',date:S.prepDate,type:'task_due',sourceKind:'tasks',sourceId:301}];S.viewer='Daughter';danceTab='Dance Home';S.streak=6;S.points=2;S.achievements=[{id:'streak_7',label:'7-day streak',earned:false},{id:'chores_25',label:'25 completed chores',earned:true}];S.recognitions=[{id:401,recognitionType:'Proud of You',message:'You worked hard.',creator:'Dad',createdAt:hubToday()+'T12:00:00Z'}]",context);
vm.runInContext("S.danceAttention=[{id:101,title:'Spring Showcase',danceType:'competition',target:'Competitions',reasons:['Performance schedule pending','Fee due tomorrow'],deadlines:[{id:'fee',title:'Fee due'}]},{id:103,title:'Moonlight costume',danceType:'costume',target:'Costumes',reasons:['Ordered, not received','Alterations needed'],deadlines:[]}];S.badgeCounts.dance=2",context);
vm.runInContext("render('dance')",context);
for(const section of ['Dance Home','Schedule','Routines','Competitions','Costumes','Dance Checklists','Spring Showcase','SCHEDULE PENDING','Costume attention','Packing progress','Studio practice','Moonlight costume needed']) assert.ok(app.innerHTML.includes(section),section);
for(const reason of ['Needs Attention','2','Fee due tomorrow','Ordered, not received','Alterations needed','Mark done: Fee due']) assert.ok(app.innerHTML.includes(reason),reason);
assert.ok(!app.innerHTML.includes('125'));
vm.runInContext("danceTab='Schedule';render('dance')",context);
assert.ok(app.innerHTML.includes('Dance practice')&&!app.innerHTML.includes('School concert'));
vm.runInContext("danceTab='Routines';render('dance')",context);
assert.ok(app.innerHTML.includes('Moonlight')&&app.innerHTML.includes('Ms. Lee'));
vm.runInContext("danceTab='Competitions';render('dance')",context);
assert.ok(app.innerHTML.includes('SCHEDULE PENDING')&&app.innerHTML.includes('Spring Showcase'));
vm.runInContext("S.events.push({id:203,title:'Spring Showcase',date:S.prepDate,visibility:'Family',sourceDanceId:101,sourceDanceKey:'competition'});openEventDetails(203)",context);
assert.ok(app.modal.includes('Spring Showcase'));
assert.ok(app.modal.includes(vm.runInContext('danceDate(S.prepDate)',context)));
vm.runInContext("danceTab='Costumes';render('dance')",context);
assert.ok(app.innerHTML.includes('Ordered · waiting')||app.innerHTML.includes('Alterations needed'));
vm.runInContext("danceTab='Dance Checklists';render('dance')",context);
assert.ok(app.innerHTML.includes('Competition Packing')&&app.innerHTML.includes('Shoes'));
vm.runInContext("S.viewer='Dad';danceTab='Competitions';render('dance')",context);
assert.ok(app.innerHTML.includes('confirmDanceDelete(101)')&&app.innerHTML.includes('mutate({action:\'archive\',id:101}')&&app.innerHTML.includes('Edit'));
assert.ok(app.innerHTML.includes('confirmArchiveSeason()'));
vm.runInContext("confirmDanceDelete(101)",context);
assert.ok(app.modal.includes('Delete Spring Showcase?'));
assert.ok(app.modal.includes('Other Dance records are kept'));
assert.ok(app.modal.includes('Cancel')&&app.modal.includes('mutate({action:\'delete\',id:101}'));
app.modal='';
vm.runInContext("confirmArchiveSeason()",context);
assert.ok(app.modal.includes('Archive Dance season?')&&app.modal.includes("action:'archive_season'"));
app.modal='';
vm.runInContext("danceRecordFilter='archived';render('dance')",context);
assert.ok(!app.innerHTML.includes('Spring Showcase'));
vm.runInContext("danceById(101).archived=true;render('dance')",context);
assert.ok(app.innerHTML.includes('Spring Showcase')&&app.innerHTML.includes('Restore'));
vm.runInContext("danceById(101).archived=false;danceRecordFilter='active';render('dance')",context);
vm.runInContext("S.viewer='Daughter';danceTab='Competitions';render('dance');confirmDanceDelete(101)",context);
assert.ok(!app.innerHTML.includes('confirmDanceDelete')&&!app.innerHTML.includes('confirmArchiveSeason')&&!app.modal.includes('Delete Spring Showcase?'));
vm.runInContext("render('tomorrow')",context);
for(const section of ["Tomorrow's Schedule",'Things To Do','Things To Pack',"Don't Forget",'School concert','Pack water bottle','Shoes','Remember shoes']) assert.ok(app.innerHTML.includes(section),section);
assert.ok(!app.innerHTML.includes('Dad private task'));
vm.runInContext("S.tasks=[{id:501,title:'Chore completed',category:'Home',who:'Daughter',chore:true,visibility:'Family',creator:'Dad',status:'done',completedAt:hubToday()+'T12:00:00Z',completedBy:'Daughter',completionHistory:[{completedAt:hubToday()+'T12:00:00Z',completedBy:'Daughter'}]},{id:502,title:'Homework',category:'School',who:'Daughter',chore:false,visibility:'Family',creator:'Dad',status:'done',completedAt:hubToday()+'T13:00:00Z',completedBy:'Daughter',completionHistory:[{completedAt:hubToday()+'T13:00:00Z',completedBy:'Daughter'}]},{id:503,title:'Rescheduled chore',category:'Home',who:'Daughter',chore:true,visibility:'Family',creator:'Dad',status:'missed',reasonAt:hubToday()+'T14:00:00Z',reasonCode:'Rescheduled',reasonExplanation:'Practice ran late',notCompletedHistory:[{person:'Daughter',timestamp:hubToday()+'T14:00:00Z',reasonCode:'Rescheduled',explanation:'Practice ran late'}]},{id:504,title:'Adult budget review',category:'Bills',who:'Dad',chore:false,visibility:'Adults',creator:'Dad',status:'done',completedBy:'Dad',completedAt:hubToday()+'T12:00:00Z',completionHistory:[{completedAt:hubToday()+'T12:00:00Z',completedBy:'Dad'}]},{id:505,title:'Jermaine Me Only task',category:'Work',who:'Dad',chore:false,visibility:'Me',creator:'Dad',status:'done',completedBy:'Dad',completedAt:hubToday()+'T12:00:00Z',completionHistory:[{completedAt:hubToday()+'T12:00:00Z',completedBy:'Dad'}]},{id:506,title:'Stephanie Me Only task',category:'Work',who:'Mom',chore:false,visibility:'Me',creator:'Mom',status:'done',completedBy:'Mom',completedAt:hubToday()+'T12:00:00Z',completionHistory:[{completedAt:hubToday()+'T12:00:00Z',completedBy:'Mom'}]}];render('recap')",context);
for(const text of ['Our Week','2','1','Not finished yet','Rescheduled','6','25 completed chores','Proud of You','You worked hard.']) assert.ok(app.innerHTML.includes(text),text);
assert.ok(app.innerHTML.includes('<b>2</b><span>Tasks completed</span>'));
assert.ok(app.innerHTML.includes('School concert')&&app.innerHTML.includes('Spring Showcase'));
assert.ok(!app.innerHTML.includes('Household follow-up')&&!app.innerHTML.includes('Dad private task'));
for(const secret of ['Adult budget review','Jermaine Me Only task','Stephanie Me Only task','125']) assert.ok(!app.innerHTML.includes(secret),secret);
assert.ok(app.innerHTML.includes('<b>1</b><span>Rescheduled</span>'));
vm.runInContext("S.recognitions=[{id:701,recognitionType:'Great Job',message:'You made your bed!',creator:'Dad',sourceTaskId:501,seenAt:'',createdAt:'2026-10-01T12:00:00Z'},{id:702,recognitionType:'Proud of You',message:'Keep shining!',creator:'Mom',sourceTaskId:501,seenAt:'',createdAt:'2026-10-02T12:00:00Z'}];S.viewer='Daughter';showRecognitionCelebration()",context);
for(const text of ['Great Job, Arielle!','Jermaine is proud of you','For completing','Chore completed','You made your bed!','Awesome! 🎉','dismissRecognition(701)']) assert.ok(app.modal.includes(text),text);
vm.runInContext("S.recognitions.find(item=>item.id===701).seenAt='2026-10-02T13:00:00Z';showRecognitionCelebration()",context);
assert.ok(app.modal.includes('Proud of You, Arielle!')&&app.modal.includes('Stephanie is proud of you'));
assert.ok(!app.modal.includes('You made your bed!'));
app.modal='';
vm.runInContext("S.viewer='Dad';showRecognitionCelebration()",context);
assert.equal(app.modal,'');
vm.runInContext("S.viewer='Dad';S.tasks=[{id:601,title:'Arielle completed task',status:'done',completedBy:'Daughter',category:'Home',who:'Daughter',visibility:'Family',creator:'Dad'}];openTaskDetails(601);recognitionForm(601)",context);
for(const type of ['Great Job','Nice Work','Streak Saver','Above & Beyond','Proud of You','Thank You']) assert.ok(app.modal.includes(type),type);
assert.ok(app.modal.includes('Give recognition'));
vm.runInContext("render('home')",context);
assert.ok(app.innerHTML.includes('Next competition: Spring Showcase')&&app.innerHTML.includes('Tomorrow Prep'));
vm.runInContext("openDanceForm('routine')",context);
for(const field of ['danceRoutineType','danceChoreographer','danceInstructor','danceScheduleInformation','danceNotes','danceCostumeId']) assert.ok(app.modal.includes(field),field);
for(const type of ['Solo','Trio','Group']) assert.ok(app.modal.includes(type),type);
vm.runInContext("openDanceForm('competition')",context);
for(const field of ['danceStartDate','danceEndDate','danceVenue','danceAddress','danceHotel','danceTravel','danceArrivalTime','danceCallTime','dancePerformanceSchedule','danceSchedulePending','danceDeadlines','danceFees']) assert.ok(app.modal.includes(field),field);
vm.runInContext("openDanceForm('costume')",context);
for(const field of ['danceOrdered','danceReceived','danceAlterationsNeeded','danceAlterationsCompleted','danceNeededBy','danceAccessories','danceShoes','danceTights']) assert.ok(app.modal.includes(field),field);
vm.runInContext("openDanceForm('checklist')",context);
for(const type of ['Competition Packing','Practice Bag','Costume Checklist','Travel Checklist']) assert.ok(app.modal.includes(type),type);
const parentDanceForm=app.modal;
vm.runInContext("S.viewer='Daughter';openDanceForm('competition');openDanceDetails(101)",context);
assert.ok(app.modal===parentDanceForm||!app.modal.includes('danceFees'));
assert.ok(!app.modal.includes('125'));
vm.runInContext("S.posts=[{id:1,by:'Mom',text:safeState('<img src=x onerror=alert(1)>'),reacts:{}}];render('board')",context);
assert.ok(!app.innerHTML.includes('<img src=x'));
assert.ok(app.innerHTML.includes('&lt;img'));
vm.runInContext("S.posts=[{id:2,by:'Dad',text:'Pack tonight',createdAt:'2026-10-02T12:00:00Z',pinned:true,important:true,ackRequired:true,acknowledgedBy:['Daughter'],reacts:{'❤️':1},comments:[{id:1,by:'Mom',text:'Already packed',createdAt:'2026-10-02T12:01:00Z'}]}];S.viewer='Dad';render('board')",context);
for(const text of ['Pinned','Important','Pack tonight','Already packed','Stephanie','1 of 3 acknowledged','Unpin','Acknowledge']) assert.ok(app.innerHTML.includes(text),text);
vm.runInContext("openPost()",context);
assert.ok(app.modal.includes('postImportant')&&app.modal.includes('postAckRequired'));
vm.runInContext("S.viewer='Daughter';openPost()",context);
assert.ok(!app.modal.includes('postImportant')&&!app.modal.includes('postAckRequired'));
const busyButton={tagName:'BUTTON',disabled:false,isConnected:true,attributes:{},setAttribute(name,value){this.attributes[name]=value},removeAttribute(name){delete this.attributes[name]}};
context.document.activeElement=busyButton;
const restoreBusyButton=vm.runInContext('pendingButton()',context);
assert.ok(busyButton.disabled&&busyButton.attributes['aria-busy']==='true');
restoreBusyButton();
assert.ok(!busyButton.disabled&&!busyButton.attributes['aria-busy']);
console.log('PASS: all screens render for three roles; user HTML is escaped.');

async function verifyQueuedForcedRefresh(){
 const pending=[];
 const isolatedApp={innerHTML:''};
 const isolated=vm.createContext({
  document:{querySelector:selector=>selector==='#app'?isolatedApp:null,getElementById:()=>null,body:{insertAdjacentHTML(){}},addEventListener(){},visibilityState:'visible'},
  window:{scrollTo(){}},localStorage:{removeItem(){}},fetch:url=>new Promise(resolve=>pending.push({url,resolve})),setInterval(){},setTimeout(){},console,
  alert(){},prompt(){return null},confirm(){return false}
 });
 vm.runInContext(fs.readFileSync('app.js','utf8'),isolated);
 assert.equal(pending.filter(item=>item.url==='/api/state').length,1);
 const forced=vm.runInContext('refresh(true)',isolated);
 assert.equal(pending.filter(item=>item.url==='/api/state').length,1);
 const state={tasks:[],posts:[],requests:[],events:[],lists:[],dance:[],notes:[],recognitions:[],activity:[],reminders:[],achievements:[],badgeCounts:{},viewer:'Dad',profiles:{Dad:{displayName:'Jermaine',role:'ADMIN'}},streak:0,points:0,timezone:'UTC'};
 const stateReply=()=>({ok:true,json:async()=>state});
 pending.find(item=>item.url==='/api/profiles').resolve({ok:true,json:async()=>({profiles:state.profiles})});
 pending.find(item=>item.url==='/api/state').resolve(stateReply());
 await new Promise(resolve=>setImmediate(resolve));
 assert.equal(pending.filter(item=>item.url==='/api/state').length,2);
 pending.filter(item=>item.url==='/api/state')[1].resolve(stateReply());
 await forced;
 assert.equal(isolatedApp.innerHTML.includes('Martin-Riley Family Hub'),true);
}

verifyQueuedForcedRefresh().then(()=>console.log('PASS: forced refresh queued behind an in-flight poll.')).catch(error=>{console.error(error);process.exitCode=1});
